### ISSUE TITLE
 If it is possible to attach a sample input / output for reference?

### ISSUE THREAD

**Issue by Frank-Dz** [maria-korosteleva/Body-Shape-Estimation#5]
Many thanks for your great work!
May I ask if it is possible to attach a sample input/output for reference?

**Comment by maria-korosteleva** [comment]
@Frank-Dz Thank you very much for your interest! 
It is possible but might take a few days until I double-check the licensing for the input samples we are using, and get to my workstation to make a run

I will update the repo and the issue as soon as I get the samples

**Comment by Frank-Dz** [comment]
> @Frank-Dz Thank you very much for your interest!
> It is possible but might take a few days until I double-check the licensing for the input samples we are using, and get to my workstation to make a run
> 
> I will update the repo and the issue as soon as I get the samples

Thank you!

Best,
Frank

**Comment by maria-korosteleva** [comment]
Hi @Frank-Dz I updated the repo with an example of input & output. Unfortunately, it is not possible to attach any of our models with garments, but I hope this synthetic example will still be helpful 😀

**Comment by Frank-Dz** [comment]
> Hi @Frank-Dz I updated the repo with an example of input & output. Unfortunately, it is not possible to attach any of our models with garments, but I hope this synthetic example will still be helpful

Thanks!

Best,
Frank
