### ISSUE TITLE
Dependencies' versions

### ISSUE THREAD

**Issue by justanhduc** [maria-korosteleva/Body-Shape-Estimation#6]
Hi @maria-korosteleva. Thanks for sharing the codes. Could you please let me know the versions of the dependencies? I ran into many errors regarding Ceres and libigl. Thanks in advance!

**Comment by maria-korosteleva** [comment]
Hi @justanhduc!  I'm sorry it took me so long to notice your request =( 

Here are the versions of libs that I was working with:
Eigen: 3.3.7
ceres: 1.14.0 
libigl: 2.0.0 or 2.1.0
OpenPose: 1.4.0
Boost: 1.68.0

I worked with versions compiled under Windows 10, Visual Studio 2017 (compiler v141), x64, Release build.

Thank you very much for pointing this out!

I'm closing this issue, pls, re-open if you find further problems with libs versions
